virt-install \
  --virt-type=kvm \
  --name vm-jenkins-1 \
  --ram 1024 \
  --vcpus 1 \
  --disk path=/var/lib/libvirt/images/jenkins1.qcow2,device=disk,bus=virtio \
  --graphics vnc,listen=0.0.0.0 \
  --noautoconsole \
  --os-variant ubuntu24.04 \
  --network network=internet-net \
  --check path_in_use=off \
  --import
