virt-install \
  --virt-type=kvm \
  --name $namekvm \
  --ram 3072 \
  --vcpus 2 \
  --disk path=/var/lib/libvirt/images/$image.qcow2,device=disk,bus=virtio \
  --graphics vnc,listen=0.0.0.0 \
  --noautoconsole \
  --os-variant ubuntu24.04 \
  --network network=internet-net \
  --check path_in_use=off \
  --import
