#
name: uat-check-kvm

on:
  push:
    branches:
    - side
  pull_request:
    branches:
    - main

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:

     - name: Checkout
       uses: actions/checkout@v2

     - name: Install kvm
       run: |
           sudo apt update > /dev/null 2>&1
           sudo apt install -y qemu-kvm libvirt-daemon-system libvirt-clients bridge-utils virtinst > /dev/null 2>&1
           
     - name: Setup kvm
       run: |
            sudo systemctl enable --now libvirtd
            sudo systemctl status libvirtd
            sudo adduser $USER kvm
            sudo adduser $USER libvirt

     - name: test format disk
       run: |
          export image=$(wget https://cloud-images.ubuntu.com/noble/current/noble-server-cloudimg-amd64.ova > /dev/null 2>&1)
          echo $image

