name: uat-check-kvm

on:
  push:
    branches:
    - side
  pull_request:
    branches:
    - main

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:

     - name: Checkout
       uses: actions/checkout@v2

     - name: Install kvm
       run: |
           sudo apt update > /dev/null 2>&1
           sudo apt install -y qemu-kvm libvirt-daemon-system libvirt-clients bridge-utils virtinst > /dev/null 2>&1
           
     - name: Setup kvm
       run: |
            sudo systemctl enable --now libvirtd
            sudo systemctl status libvirtd
            sudo adduser $USER kvm
            sudo adduser $USER libvirt
            echo 'export LIBVIRT_DEFAULT_URI=qemu:///system' >> ~/.bashrc
            source ~/.bashrc
            sudo usermod -a -G libvirt,kvm $USER
            newgrp libvirt
            sudo sed -i 's/^#\?\s*unix_sock_group = "libvirt"/unix_sock_group = "libvirt"/' /etc/libvirt/libvirtd.conf
            sudo sed -i 's/^#\?\s*unix_sock_rw_perms = "0770"/unix_sock_rw_perms = "0770"/' /etc/libvirt/libvirtd.conf

            # 2. MUST RESTART agar perubahan socket di-apply
            sudo systemctl restart libvirtd

            # 3. Tambahkan user ke grup
            sudo usermod -aG libvirt,kvm $USER

            # 4. Set Environment Variable langsung di level process (tanpa .bashrc)
            export LIBVIRT_DEFAULT_URI="qemu:///system"
            sudo systemctl restart libvirtd
            sudo systemctl status libvirtd

     - name: install image
       run: |
          export image=noble-server-cloudimg-amd64.ova
          wget https://cloud-images.ubuntu.com/noble/current/$image> /dev/null 2>&1
          echo "---------berhasil ambil image---------------"
          ls
          mv $image image
          cd image
          ls -lah
          echo "-------image berhasil move ke dir image-----"
          cd ../
          ./format-img-ova-toqcow2.sh
          cd image 
          ls -lah
          pwd
          echo "--------berhasil di format------------------"

     - name: cek via virsh
       run: |
           cd network
           chmod +x create-network.sh
           ./create-network.sh
           sudo virsh net-list --all 
           sudo virsh net-autostart internet-net 
           sudo virsh list --all

     - name: start sample kvm
       run: |
            sudo ls -lah /var/lib/libvirt/images/
            cat << 'EOF' > create-kvm2.sh
            virt-install \
            --connect qemu:///system \
            --virt-type=kvm \
            --name vm-jenkins-1 \
            --ram 1024 \
            --vcpus 1 \
            --disk path=/var/lib/libvirt/images/jenkins1.qcow2,device=disk,bus=virtio \
            --graphics vnc,listen=0.0.0.0 \
            --noautoconsole \
            --os-variant ubuntu24.04 \
            --network network=internet-net \
            --check path_in_use=off \
            --import
            EOF

            export imagetarget=$(sudo ls /var/lib/libvirt/images/ | grep -i '\.qcow2$' | head -n 1)
            
            
            sed -i s'/jenkins1.qcow2/$imagetarget/' create-kvm2.sh

            chmod +x create-kvm2.sh
            sudo ./create-kvm2.sh
            sudo virsh list --all

           

          
          
 #         export image=noble-server-cloudimg-amd64
 #       tar -xvf image/$image.ova > hasil.txt
          
          
